### PR TITLE
Fix cropping CLI

### LINKED ISSUE #11: cropping does not do anything at all
In e1ca17b9, the complete functionality of `ocrd-anybaseocr-crop` has been commented out. All it does now is print the `@imageFilename`. What's going on?

### PR DESCRIPTION
**Pull request by wrznr**
As observed by @bertsky, the latest changes to the code disabled
the cropping functionality. Since DFKI cropping is the only
dedicated processor for this task in OCR-D, we need it asap. This
commit proposes the necessary changes to bring cropping back to
work. However, it is far from optimal. I.e. the heavy dependencies
introduced by the machine-learnign based tools in this repo should
be somehow circumvented for the relatively simple rule-based
cropping processor.

Fixes #11.

### CODE REVIEW

**Comment by khurramHashmi** [comment]
We could not commit all of the mentioned changes, but we changed cropping, binarization, and deskewing scripts. They should work again now.

**Comment by wrznr** [comment]
@khurramHashmi Why didn't you just merge my PR? Now we have a master branch which is still not working as expected (i.e. `AlternativeImage`) and my branch which cannot be merged anymore. This is very frustrating.

**Comment by mjenckel** [comment]
@wrznr I think this is my fault, as I told Khurram to fix cropping and he started working on the fix in parallel to your pull request. This made the pull request not compatible with our local version and we tried to incorporate all your changes manually BEFORE you updated your pull request (i.e. AlternativeImage functionality). We will adapt those changes quickly (today) as well to get the desired functionality working. I am sorry for the inconvenience.

**Comment by wrznr** [comment]
@mjenckel So I can safely close this one, right?

**Pull request closed without merging**
