### PR TITLE
Remove CI tests for old Python versions

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
It looks like the CI tests are broken. Running less tests should not cause a failure of the remaining ones.

**Comment by bertsky** [comment]
> It looks like the CI tests are broken. Running less tests should not cause a failure of the remaining ones.

It doesn't. Just the CI has not been run for quite a while, because there was no change to trigger it. And during that time, other packages broke – the usual problem.

In this case, we just need to downgrade Tensorflow (or rather, tf.keras).

**Comment by stweil** [comment]
See new issue #107.

**Comment by stweil** [comment]
What about merging this PR?

**Comment by stweil** [comment]
Meanwhile this PR was superseded by the commits 577e4582, bf02f08c and 73a2eced, so I close it now.,

**Pull request closed without merging**
