### PR TITLE
adapt to Numpy and Pillow deprecations

### PR DESCRIPTION
**Pull request by bertsky**

### CODE REVIEW

**Comment by bertsky** [comment]
@kba I really think this should be merged soon – we still do need the cropper here.

Should I add some Dockerhub CD as well?

**Comment by stweil** [comment]
Ping?

**Comment by bertsky** [comment]
> Should I add some Dockerhub CD as well?

done. Now needs `$DOCKERHUB_USER` and `$DOCKERHUB_PASS` in CircleCI, as well.

@kba?

**Comment by kba** [comment]
> > Should I add some Dockerhub CD as well?
> 
> done. Now needs `$DOCKERHUB_USER` and `$DOCKERHUB_PASS` in CircleCI, as well.
> 
> @kba?

Sry for the delay. Variables added.

**Pull request merged**
